[package]
name = "hts_engine_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["htsvoice"]
htsvoice = ["dep:nom"]

[dependencies]
libc="*"
anyhow = "1.0.75"
byteorder = "1.5.0"
thiserror = "1.0"

regex = "1.10.2"

nom = { version = "7.1.3", optional = true }
approx = "0.5.1"
