[package]
name = "jbonsai"
version = "0.1.0"
edition = "2021"

rust-version = "1.65.0"

[features]
default = ["htsvoice"]
htsvoice = ["dep:nom"]

[dependencies]
anyhow = "1.0.75"
byteorder = "1.5.0"
thiserror = "1.0"

regex = "1.10.2"

nom = { version = "7.1.3", optional = true }
approx = "0.5.1"
